# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eb614f912d5f49d00498e14a6108c5a709b336e5e2b62a7312ed69d7e4ce5ed39879061028c814fe8e8221614aac586fe772bec0055e3cbe7b931b6993d0ec6

test:
  secret_key_base: 5dc8adab45f6fa979a4d9a69325575d0918d0dded65683681a40a2588577da60c0efa71abd16fbc7b8b0340c9dda6d6db9639630be8c3f5c5a1d001632d72aec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
